name: test
channels:
  - conda-forge
  - defaults
dependencies:
  # obspy
  - decorator
  - lxml
  - matplotlib
  - numpy >= 2.0.0rc2
  # dummy package needed to install the np2 rc via conda
  - conda-forge/label/numpy_rc::_numpy_rc
  - scipy
  - requests
  - setuptools
  # see #3258
  - sqlalchemy < 2.0
  # soft dependencies
  - cartopy
  - geographiclib
  - pyshp
  # tests
  - packaging
  - pyproj
  - pytest
  - pytest-cov
  - pytest-json-report >= 1.4
